# Generated by Django 2.2.1 on 2019-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='city',
            field=models.CharField(default='Seatac', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='state_abbr',
            field=models.CharField(default='WA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='zip_code',
            field=models.CharField(default='98188', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='nickname',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
