# Generated by Django 2.2.1 on 2019-08-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('FuelTrackerApp', '0004_auto_20190818_2121'),
	]

	operations = [
		migrations.AddField(
			model_name='receipt',
			name='note',
			field=models.CharField(blank=True, max_length=50, null=True),
		),
	]
