# Generated by Django 2.2.1 on 2019-08-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelTrackerApp', '0005_receipt_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='mi_since_last',
            field=models.FloatField(default=320),
            preserve_default=False,
        ),
    ]
